### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by ffallah** [simplestaking/tezedge#190]
I am getting the following error on Debian 9 :
```
~/tezedge$ docker-compose pull
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by mrjoe7** [comment]
You will have to update your docker-compose to version which has support for 3.0 (of higher) version of yaml file.

**Comment by ffallah** [comment]
Why did you close this before resolving the issue ?
I am on Debian 9 with official repository and latest version of docker-compose which is available of Debian 9 and your software doesnt support it.
So remove Debian 9 from your supported OSes if you are not going to resolve the issue.

**Comment by mrjoe7** [comment]
Sorry, not used to github issues. We can reopen this ticket

**Comment by mrjoe7** [comment]
I have downgraded docker compose yaml version. Please check if you still see the error

**Comment by ffallah** [comment]
Thanks, The issue is resolved.
