### ISSUE TITLE
Error Invalid value for '--protocol-runner <PATH>':

### ISSUE THREAD

**Issue by songproducer** [simplestaking/tezedge#99]
Trying on Ubuntu now.

> error: Invalid value for '--protocol-runner <PATH>': Tezos protocol runner executable not found at './target/debug/protocol-runner'

**Comment by mrjoe7** [comment]
Please post full logs. There should be more info why protocol-runner did not compile.

**Comment by songproducer** [comment]
> u19.so", sha256_checksum_url: "https://gitlab.com/simplestaking/tezos/uploads/63c5be56243ef892cb8418d9ca9a11ce/libtezos-ffi-ubuntu19.so.sha256" }
> 
> --- stderr
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>  30 52.9M   30 16.2M    0     0  31352      0  0:29:29  0:09:02  0:20:27 25339
> curl: (18) transfer closed with 38455972 bytes remaining to read
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `[127, 253, 24, 106, 91, 83, 253, 25, 124, 241, 153, 77, 187, 75, 29, 211, 4, 148, 100, 253, 19, 225, 150, 163, 6, 110, 117, 3, 173, 50, 104, 192]`,
>  right: `[109, 6, 32, 162, 17, 147, 118, 22, 52, 17, 231, 86, 225, 80, 147, 216, 248, 189, 225, 61, 143, 123, 233, 187, 52, 135, 109, 106, 181, 89, 177, 174]`: libtezos.o SHA256 mismatch', tezos/interop/build.rs:151:17
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
>     Finished dev [unoptimized + debuginfo] target(s) in 0.17s
>      Running `target/debug/light-node -d /tmp/tezedge -B /tmp/tezedge --network babylonnet --protocol-runner ./target/debug/protocol-runner`
> error: Invalid value for '--protocol-runner <PATH>': Tezos protocol runner executable not found at './target/debug/protocol-runner'
>

**Comment by mrjoe7** [comment]
It seems that your download from gitlab.com failed
```
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
30 52.9M 30 16.2M 0 0 31352 0 0:29:29 0:09:02 0:20:27 25339
curl: (18) transfer closed with 38455972 bytes remaining to read
``` so you ended with corrupted `libtezos-ffi-ubuntu19.so"`file. Try to run `cargo clean` to clean corrupted files and try again.

**Comment by mrjoe7** [comment]
If this problem persist we will have consider moving compiled binaries to a more reliable CDN.

**Comment by songproducer** [comment]
Thanks, issue solved!
